### PR TITLE
Throw exception if appending using sort_and_finalize will create unordered index

### LINKED ISSUE #1734: Using sort_and_finalize_staged_data with append can create unordered index
**Describe the bug**
When `sort_and_finalize_staged_data` is used with `mode=StagedDataFinalizeMethod.APPEND` it allows to append index such that the overall index becomes out of order. For example it's possible for the appended index values to be less than the last index value in storage.

**Steps to reproduce**
```python
import pandas as pd
import numpy as np
import arcticdb as adb
from arcticdb.version_store.library import StagedDataFinalizeMethod

ac = adb.Arctic("lmdb://test")
lib = ac.get_library("test", create_if_missing=True)
initial_df = pd.DataFrame({"col": [1, 3]}, index=pd.DatetimeIndex([np.datetime64('2023-01-01'), np.datetime64('2023-01-03')], dtype="datetime64[ns]"))
lib.write("sym", initial_df)
df1 = pd.DataFrame({"col": [2]}, index=pd.DatetimeIndex([np.datetime64('2023-01-02')], dtype="datetime64[ns]"))
lib.write("sym", df1, staged=True)
lib.sort_and_finalize_staged_data("sym", mode=StagedDataFinalizeMethod.APPEND)
print(lib.read("sym"))
```

Output:
```
            col
2023-01-01    1
2023-01-03    3
2023-01-02    2
```

**Expected behavior**
It should behave just like `Library.append` and throw an exception.

**OS, Python, Arctic versions**
```
Python: 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
OS: Windows-10-10.0.22631-SP0
ArcticDB: 4.5.0rc1
```

### PR DESCRIPTION
**Pull request by vasil-pashov**
#### Reference Issues/PRs
Resolve #1734

#### Checklist

<details>
  <summary>
   Checklist for code changes...
  </summary>
 
 - [ ] Have you updated the relevant docstrings, documentation and copyright notice?
 - [ ] Is this contribution tested against [all ArcticDB's features](../docs/mkdocs/docs/technical/contributing.md)?
 - [ ] Do all exceptions introduced raise appropriate [error messages](https://docs.arcticdb.io/error_messages/)?
 - [ ] Are API changes highlighted in the PR description?
 - [ ] Is the PR labelled as enhancement or bug so it appears in autogenerated release notes?
</details>

### CODE REVIEW

File: cpp/arcticdb/version/version_core.cpp [hunk 1]
```diff
@@ -1299,6 +1298,15 @@ VersionedItem sort_merge_impl(
 
             read_query.clauses_.emplace_back(std::make_shared<Clause>(MergeClause{timeseries_index, SparseColumnPolicy{}, stream_id, pipeline_context->descriptor()}));
             auto segments = read_and_process(store, pipeline_context, read_query, ReadOptions{}, pipeline_context->incompletes_after());
+            if (options.append_ && update_info.previous_index_key_.has_value() &&
+                update_info.previous_index_key_->end_time() - 1 > std::get<timestamp>(TimeseriesIndex::start_value_for_segment(segments[0].segment_.value()))) {
+                store->remove_keys(delete_keys).get();
+                user_input::raise<ErrorCode::E_INVALID_USER_ARGUMENT>(
+                    "Cannot append index starting at {} to data frame with index ending at {}",
+                    std::get<timestamp>(TimeseriesIndex::start_value_for_segment(segments[0].segment_.value())),
+                    update_info.previous_index_key_->start_time()
```
Comment (alexowens90) [inline cpp/arcticdb/version/version_core.cpp:1307]: Update this too

File: python/tests/unit/arcticdb/version_store/test_sort_merge.py [hunk 2]
```diff
@@ -176,17 +177,26 @@ def test_appended_values_are_after(self, lmdb_library):
...
         initial_df = pd.DataFrame({"col": [1, 3]}, index=pd.DatetimeIndex([np.datetime64('2023-01-01'), np.datetime64('2023-01-03')], dtype="datetime64[ns]"))
         lib.write("sym", initial_df)
         df1 = pd.DataFrame({"col": [2]}, index=pd.DatetimeIndex([np.datetime64('2023-01-02')], dtype="datetime64[ns]"))
         lib.write("sym", df1, staged=True)
-        with pytest.raises(Exception) as exception_info:
+        with pytest.raises(UserInputException) as exception_info:
             lib.sort_and_finalize_staged_data("sym", mode=StagedDataFinalizeMethod.APPEND)
         assert "append" in str(exception_info.value)
 
+    def test_appended_df_start_same_as_df_end(self, lmdb_library):
```
Comment (alexowens90) [inline python/tests/unit/arcticdb/version_store/test_sort_merge.py:190]: This test would be better with multiple rows in both the existing and appended data, and different values in the column

**Review by alexowens90 — APPROVED** [review]
