### PR TITLE
bugfix/1247: Don't create an lmdb library if the name is invalid.

### LINKED ISSUE #1247: LMDB on Windows creates unusable libraries when using invalid characters
### Describe the bug

When using any of the [unallowed windows directory characters](https://stackoverflow.com/questions/1976007/what-characters-are-forbidden-in-windows-and-linux-directory-names) in a library name on Windows LMDB, the library is written but is unusable.

Creating the library appropriately raises an exception but when listing the libraries it wrongly appears in the list and it's unusable.

### Steps/Code to Reproduce

```
>>> from arcticdb import Arctic
>>> ac = Arctic("lmdb://test")
>>> ac.create_library("lib|1")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\iddil\source\venvs\310\Lib\site-packages\arcticdb\arctic.py", line 290, in create_library
    return self.get_library(name)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\iddil\source\venvs\310\Lib\site-packages\arcticdb\arctic.py", line 239, in get_library
    lib = self[name]
          ~~~~^^^^^^
  File "C:\Users\iddil\source\venvs\310\Lib\site-packages\arcticdb\arctic.py", line 190, in __getitem__
    self._library_manager.get_library(name, storage_override),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
arcticdb_ext.exceptions.InternalException: (create_directories: The filename, directory name, or volume label syntax is incorrect.: "C:\Users\iddil\test\test\lib|1")
>>> # Listing the libraries contains the library which failed on creation
>>> ac.list_libraries()
['lib|1']
>>> # We can't access the library
>>> lib = ac['lib|1']
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\iddil\source\venvs\310\Lib\site-packages\arcticdb\arctic.py", line 190, in __getitem__
    self._library_manager.get_library(name, storage_override),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
arcticdb_ext.exceptions.InternalException: (create_directories: The filename, directory name, or volume label syntax is incorrect.: "C:\Users\iddil\test\test\lib|1")
```

### Expected Results

A better exception is raised when using an invalid character on Windows LMDB and list_libraries should not contain the failed library.

### OS, Python Version and ArcticDB Version

Windows, Python 3.11.7

### Backend storage used

LMDB

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by muhammadhamzasajjad**
#### Reference Issues/PRs
Fixes #1247 

#### Checklist

<details>
  <summary>
   Checklist for code changes...
  </summary>
 
 - [ ] Have you updated the relevant docstrings, documentation and copyright notice?
 - [ ] Is this contribution tested against [all ArcticDB's features](../docs/mkdocs/docs/technical/contributing.md)?
 - [ ] Do all exceptions introduced raise appropriate [error messages](https://docs.arcticdb.io/error_messages/)?
 - [ ] Are API changes highlighted in the PR description?
 - [ ] Is the PR labelled as enhancement or bug so it appears in autogenerated release notes?
</details>

### CODE REVIEW

File: cpp/arcticdb/storage/lmdb/lmdb_storage.cpp [hunk 1]
```diff
@@ -259,6 +259,23 @@ void LmdbStorage::do_iterate_type(KeyType key_type, const IterateTypeVisitor& vi
     }
 }
 
+bool LmdbStorage::do_is_path_valid(const std::string& pathString) {
```
Comment (vasil-pashov) [inline cpp/arcticdb/storage/lmdb/lmdb_storage.cpp:262]: std::string_view makes more sense here.

File: cpp/arcticdb/util/name_validation.cpp [hunk 2]
```diff
@@ -118,8 +119,14 @@ void verify_library_path_part(const std::string& library_part, char delim) {
     }
 }
 
-void verify_library_path_on_write(const StringId& library_path) {
+void verify_library_path_on_write(const std::shared_ptr<Store>& store, const StringId& library_path) {
```
Comment (vasil-pashov) [inline cpp/arcticdb/util/name_validation.cpp:122]: Avoid passing const ref to std::shared_pointer in favor of regular const pointer or const ref, unless the code is interested in some particular property of the shared_pointer (for example it want's to copy the shared pointer).

see [here](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Rf-smart) and [here](https://herbsutter.com/2013/06/05/gotw-91-solution-smart-pointer-parameters/)

**Comment by DrNickClarke** [comment]
Looks good to me

File: python/tests/integration/arcticdb/test_lmdb.py [hunk 3]
```diff
@@ -102,6 +102,29 @@ def test_lmdb_malloc_trim(lmdb_storage):
...
+
+    valid_libs = ["lib#~@,1", "lib{)[.1", "!lib$%^"]
+    for lib in valid_libs:
+        ac.create_library(lib)
+    assert set(ac.list_libraries()) == set(valid_libs)
+
+@pytest.mark.skipif(sys.platform == "win32", reason="Windows has different file path name restrictions")
+def test_valid_lib_name_linux(lmdb_storage):
+    ac = lmdb_storage.create_arctic()
+    valid_libs = ["lib?1", "lib:1", "lib|1", "lib ", "lib#~@,1", "lib{)[.1", "!lib$%^"]
```
Comment (vasil-pashov) [inline python/tests/integration/arcticdb/test_lmdb.py:123]: Use parametrized test

File: python/tests/integration/arcticdb/test_lmdb.py [hunk 4]
```diff
@@ -102,6 +102,30 @@ def test_lmdb_malloc_trim(lmdb_storage):
...
+    with pytest.raises(UserInputException) as e:
+        ac.create_library(invalid_lib_name)
+
+    assert ac.list_libraries() == []
+
+def is_valid_lmdb_lib_name(lmdb_storage, lib_name):
+    ac = lmdb_storage.create_arctic()
+    ac.create_library(lib_name)
+
+    return ac.list_libraries() == [lib_name]
```
Comment (vasil-pashov) [inline python/tests/integration/arcticdb/test_lmdb.py:118]: I'd add this inside the tests instead of separating it in a function. While it helps avoiding code duplication  it has the side effect of actually creating a library. I wouldn't expect a function checking if the name is valid to create a library.

File: cpp/arcticdb/storage/lmdb/lmdb_storage.cpp [hunk 5]
```diff
@@ -259,6 +259,23 @@ void LmdbStorage::do_iterate_type(KeyType key_type, const IterateTypeVisitor& vi
     }
 }
 
+bool LmdbStorage::do_is_path_valid(const std::string_view pathString) const {
+#ifdef _WIN32
+    std::string_view invalid_win32_chars = "<>:\"|?*";
```
Comment (alexowens90) [inline cpp/arcticdb/storage/lmdb/lmdb_storage.cpp:264]: This list is not exhaustive:
https://stackoverflow.com/questions/1976007/what-characters-are-forbidden-in-windows-and-linux-directory-names
There are also a whole bunch of other reserved filenames that would fail
https://learn.microsoft.com/en-us/windows/win32/fileio/naming-a-file

File: cpp/arcticdb/storage/lmdb/lmdb_storage.cpp [hunk 6]
```diff
@@ -259,6 +259,23 @@ void LmdbStorage::do_iterate_type(KeyType key_type, const IterateTypeVisitor& vi
...
+    auto found = pathString.find_first_of(invalid_win32_chars);
+    if (found != std::string::npos) {
+        return false;
+    }
+
+    if (!pathString.empty() && (pathString.back() == '.' || std::isspace(pathString.back()))) {
+        return false;
+    }
+#else
+    (void) pathString; // suppress -Werror=unused-parameter
```
Comment (alexowens90) [inline cpp/arcticdb/storage/lmdb/lmdb_storage.cpp:274]: Use `ARCTICDB_UNUSED` instead of this

File: cpp/arcticdb/util/name_validation.cpp [hunk 7]
```diff
@@ -118,8 +119,14 @@ void verify_library_path_part(const std::string& library_part, char delim) {
     }
 }
 
-void verify_library_path_on_write(const StringId& library_path) {
+void verify_library_path_on_write(const Store* store, const StringId& library_path) {
```
Comment (alexowens90) [inline cpp/arcticdb/util/name_validation.cpp:122]: Don't pass around raw pointers if you can help it, just pass in a copy of the shared pointer

File: cpp/arcticdb/util/name_validation.cpp [hunk 8]
```diff
@@ -118,8 +119,14 @@ void verify_library_path_part(const std::string& library_part, char delim) {
...
     verify_name("library name", library_path, true, UNSUPPORTED_S3_CHARS);
+    if(!store->is_path_valid(library_path)) {
```
Comment (alexowens90) [inline cpp/arcticdb/util/name_validation.cpp:124]: You can get rid of this `if` using `user_input::check`

File: python/tests/integration/arcticdb/test_lmdb.py [hunk 9]
```diff
@@ -102,6 +102,30 @@ def test_lmdb_malloc_trim(lmdb_storage):
     lib = ac.create_library("test_lmdb_malloc_trim")
     lib._nvs.trim()
 
+@pytest.mark.skipif(sys.platform != "win32", reason="Non Windows platforms have different file path name restrictions")
+@pytest.mark.parametrize("invalid_lib_name", ["lib?1", "lib:1", "lib|1", "lib.", "lib "])
```
Comment (alexowens90) [inline python/tests/integration/arcticdb/test_lmdb.py:106]: This testing is not comprehensive of all of the disallowed characters in `invalid_win32_chars`

File: cpp/arcticdb/util/name_validation.cpp (hunk 7 above)
Comment (muhammadhamzasajjad) [reply cpp/arcticdb/util/name_validation.cpp:122]: I was using shared pointer. But I switched to raw after this [comment](https://github.com/man-group/ArcticDB/pull/1481#discussion_r1557486377)

File: python/tests/integration/arcticdb/test_lmdb.py (hunk 9 above)
Comment (muhammadhamzasajjad) [reply python/tests/integration/arcticdb/test_lmdb.py:106]: The chars `*<>` are already disallowed for libraries in all storages [here](https://github.com/man-group/ArcticDB/blob/master/cpp/arcticdb/util/name_validation.cpp#L123) and tested [here](https://github.com/man-group/ArcticDB/blob/master/python/tests/integration/arcticdb/test_arctic_library_management.py#L243).

File: cpp/arcticdb/storage/lmdb/lmdb_storage.cpp (hunk 5 above)
Comment (muhammadhamzasajjad) [reply cpp/arcticdb/storage/lmdb/lmdb_storage.cpp:264]: I did look at the list of other [reserved filenames](https://learn.microsoft.com/en-us/windows/win32/fileio/naming-a-file) while working on the fix. But the docs were strictly saying "reserved names for the **name of a file**". In fact, I tested this and I was able to create libraries with names such as `CON, PRN, COM0` which successfully created folders with these names. These are reserved names but not strictly disallowed and that's why I allowed these names.

Comment (alexowens90) [reply cpp/arcticdb/storage/lmdb/lmdb_storage.cpp:264]: Aha OK that makes sense. I think it's worth adding a comment here explaining all this, as it won't be obvious to the next person reading it.

File: cpp/arcticdb/util/name_validation.cpp (hunk 7 above)
Comment (muhammadhamzasajjad) [inline cpp/arcticdb/util/name_validation.cpp:122]: @alexowens90, I am not sure how your comment about "switching from raw pointer to shared pointer" got deleted while I was editing my comment.
Anyway, I was using a using a shared pointer until this comment by Vasil. I think it would be helpful to choose a coding style across the team.
