### PR TITLE
Enhancement/612/read batch to catch all exceptions

### LINKED ISSUE #612: read_batch should catch all exceptions from individual queries and return what data it can
#531 covers missing version-style errors

This should extend that implementation to cover other errors, such as missing index keys, missing data keys, etc

### PR DESCRIPTION
**Pull request by alexowens90**
Closes #612

The previous behaviour of `Library.read_batch` and `NativeVersionStore.batch_read` was to throw an exception if there was an issue retrieving **any** of the requested symbol/version pairs. For backwards compatibility reasons, this behaviour has been maintained for `NativeVersionStore.batch_read`.

For `Library.read_batch`, this has been changed. A `DataError` object will now be returned in the position in the list returned corresponding to the symbol/version pair there was an issue retrieving. This contains the symbol and version requested, and the exception string thrown. For two well-defined categories of error, the error category and specific error code are also included:

- ErrorCategory.MISSING_DATA - ErrorCode.E_NO_SUCH_VERSION: The version requested by the user does not exist
- ErrorCategory.STORAGE - ErrorCode.E_KEY_NOT_FOUND: At least one of the keys required to read the specified version does not exist in the storage.

Otherwise these fields of the `DataError` object are left as `None`.

### CODE REVIEW

File: cpp/arcticdb/version/local_versioned_engine.cpp [hunk 1]
```diff
@@ -344,16 +344,17 @@ std::pair<VersionedItem, FrameAndDescriptor> LocalVersionedEngine::read_datafram
         if(opt_false(read_options.incompletes_)) {
             log::version().warn("No index:  Key not found for {}, will attempt to use incomplete segments.", stream_id);
             identifier = stream_id;
+        } else {
+            missing_data::raise<ErrorCode::E_NO_SUCH_VERSION>(
+                    "read_dataframe_version: version query '{}' not found for symbol '{}'", version_query, stream_id);
```
Comment (mehertz) [inline cpp/arcticdb/version/local_versioned_engine.cpp:349]: How can you not find a query? Does this mean no version matching the query or something like that?

File: cpp/arcticdb/version/local_versioned_engine.cpp [hunk 2]
```diff
@@ -1028,33 +1029,64 @@ std::vector<std::pair<VersionedItem, FrameAndDescriptor>> LocalVersionedEngine::
...
-std::vector<std::pair<VersionedItem, FrameAndDescriptor>> LocalVersionedEngine::temp_batch_read_internal_direct(
+std::vector<std::variant<ReadVersionOutput, DataError>> LocalVersionedEngine::temp_batch_read_internal_direct(
     const std::vector<StreamId> &stream_ids,
     const std::vector<VersionQuery> &version_queries,
     std::vector<ReadQuery> &read_queries,
     const ReadOptions &read_options) {
     py::gil_scoped_release release_gil;
+    // This read option should always be set when calling batch_read
+    internal::check<ErrorCode::E_ASSERTION_FAILURE>(read_options.batch_throw_on_missing_version_.has_value(),
+                                                    "ReadOptions::batch_throw_on_missing_version_ should always be set here");
```
Comment (mehertz) [inline cpp/arcticdb/version/local_versioned_engine.cpp:1040]: Wasn't this not going to be set from `_store`?

File: cpp/arcticdb/entity/data_error.hpp [hunk 3]
```diff
@@ -0,0 +1,121 @@
...
+#include <string>
+
+#include <fmt/format.h>
+
+#include <arcticdb/pipeline/query.hpp>
+
+namespace arcticdb::entity {
+
+enum class VersionRequestType: uint32_t {
+    SNAPSHOT,
```
Comment (willdealtry) [inline cpp/arcticdb/entity/data_error.hpp:19]: This is quite similar to the LoadType enum, do they need to be kept in sync with each other for ever? Might it be worth having a function that converts from one to the other, i.e. from the thing we tried to the class of operation that failed?

File: cpp/arcticdb/pipeline/query.hpp [hunk 4]
```diff
@@ -110,8 +110,15 @@ struct SpecificVersionQuery {
     SignedVersionId version_id_;
 };
 
+using VersionQueryType = std::variant<
```
Comment (willdealtry) [inline cpp/arcticdb/pipeline/query.hpp:113]: I like this, it is definitely better

File: cpp/arcticdb/version/local_versioned_engine.hpp [hunk 5]
```diff
@@ -273,18 +274,18 @@ class LocalVersionedEngine : public VersionedEngine {
...
         bool validate_index);
 
-    std::vector<std::pair<VersionedItem, FrameAndDescriptor>> batch_read_keys(
+    std::vector<ReadVersionOutput> batch_read_keys(
         const std::vector<AtomKey> &keys,
         const std::vector<ReadQuery> &read_queries,
         const ReadOptions& read_options);
 
-    std::vector<std::pair<VersionedItem, FrameAndDescriptor>> batch_read_internal(
+    std::vector<std::variant<ReadVersionOutput, DataError>> batch_read_internal(
```
Comment (willdealtry) [inline cpp/arcticdb/version/local_versioned_engine.hpp:282]: Did you consider std::expected?

File: cpp/arcticdb/version/versioned_engine.hpp [hunk 6]
```diff
@@ -23,6 +23,18 @@ namespace arcticdb::version_store {
 using namespace arcticdb::entity;
 using namespace arcticdb::pipelines;
 
+struct ReadVersionOutput {
```
Comment (willdealtry) [inline cpp/arcticdb/version/versioned_engine.hpp:26]: Nicer as a class than pair I think, we should make this the general pattern

**Review by willdealtry — APPROVED** [review]

File: cpp/arcticdb/version/local_versioned_engine.cpp [hunk 7]
```diff
@@ -1066,16 +1098,36 @@ std::vector<std::pair<VersionedItem, FrameAndDescriptor>> LocalVersionedEngine::
...
+    read_versions_or_errors.reserve(stream_ids.size());
     for (size_t idx=0; idx < stream_ids.size(); idx++) {
         auto version_query = version_queries.size() > idx ? version_queries[idx] : VersionQuery{};
         auto read_query = read_queries.size() > idx ? read_queries[idx] : ReadQuery{};
-        results_fut.push_back(read_dataframe_version_internal(stream_ids[idx],
-                                                              version_query,
-                                                              read_query,
-                                                              read_options));
+        // TODO: https://github.com/man-group/ArcticDB/issues/241
+        // Remove this try-catch in favour of the implementation in temp_batch_read_internal_direct as part of #241
```
Comment (mehertz) [inline cpp/arcticdb/version/local_versioned_engine.cpp:1107]: 241 will remove temp_batch_read_internal_direct surely?

File: cpp/arcticdb/version/python_bindings.cpp [hunk 8]
```diff
@@ -130,6 +132,20 @@ void register_bindings(py::module &version, py::exception<arcticdb::ArcticExcept
...
+            .value("LATEST", VersionRequestType::LATEST);
+
+    py::class_<DataError, std::shared_ptr<DataError>>(version, "DataError")
+            .def_property_readonly("symbol", &DataError::symbol)
+            .def_property_readonly("version_request_type", &DataError::version_request_type)
+            .def_property_readonly("version_request_data", &DataError::version_request_data)
+            .def_property_readonly("error_code", &DataError::error_code)
+            .def_property_readonly("error_category", &DataError::error_category)
+            .def_property_readonly("exception_string", &DataError::exception_string)
+            .def("__repr__", &DataError::to_string);
```
Comment (mehertz) [inline cpp/arcticdb/version/python_bindings.cpp:148]: This isn't a `__repr__`. `__repr__` would print something like `DataError(error_code=..., error_category=...)`.

I think this should be `__str__`.

File: python/tests/integration/arcticdb/test_arctic.py [hunk 9]
```diff
@@ -1235,6 +1236,163 @@ def test_read_batch_unhandled_type(arctic_library):
...
+    assert batch[1].error_category == ErrorCategory.MISSING_DATA
+
+    assert isinstance(batch[2], DataError)
+    assert batch[2].symbol == "s2"
+    assert batch[2].version_request_type == VersionRequestType.SPECIFIC
+    assert batch[2].version_request_data == 1
+    assert batch[2].error_code == ErrorCode.E_NO_SUCH_VERSION
+    assert batch[2].error_category == ErrorCategory.MISSING_DATA
+
+
```
Comment (mehertz) [inline python/tests/integration/arcticdb/test_arctic.py:1395]: What if the vref key exists but the version key doesn't?

File: cpp/arcticdb/version/local_versioned_engine.cpp (hunk 2 above)
Comment (mehertz) [reply cpp/arcticdb/version/local_versioned_engine.cpp:1040]: oh, does that never call into here somehow?

File: cpp/arcticdb/entity/data_error.hpp (hunk 3 above)
Comment (mehertz) [reply cpp/arcticdb/entity/data_error.hpp:19]: I was a bit concerned about this as well. Not a blocker but good if we can keep them in sync somehow.

File: cpp/arcticdb/version/local_versioned_engine.hpp (hunk 5 above)
Comment (poodlewars) [reply cpp/arcticdb/version/local_versioned_engine.hpp:282]: That's c++ 23, no?

**Review by poodlewars — APPROVED** [review]
Assume the other batch read methods (metadata, description, yadayada, are going to change to match this pattern soon too?

File: python/arcticdb/version_store/library.py [hunk 10]
```diff
@@ -876,8 +876,10 @@ def read_batch(
 
         Returns
         -------
-        List[VersionedItem]
+        List[Union[VersionedItem, DataError]]
```
[the remark this answers is not in the document]
Comment (alexowens90) [reply python/arcticdb/version_store/library.py:879]: I can't really think of a good name that isn't similar to `VersionedItemOrDataError`, at which point it doesn't help. Open to ideas though.

File: cpp/arcticdb/version/python_bindings.cpp [hunk 11]
```diff
@@ -189,13 +205,22 @@ void register_bindings(py::module &version, py::exception<arcticdb::ArcticExcept
 
 
 
-    auto adapt_read_dfs = [](std::vector<ReadResult> && ret) -> py::list {
+    auto adapt_read_dfs = [](std::vector<std::variant<ReadResult, DataError>> && ret) -> py::list {
```
[the remark this answers is not in the document]
Comment (alexowens90) [reply cpp/arcticdb/version/python_bindings.cpp:208]: Same point as in the Python layer, I think a variant with two elements is clearer than a name that just includes both somehow

**Comment by alexowens90** [comment]
> Assume the other batch read methods (metadata, description, yadayada, are going to change to match this pattern soon too?

Yes, @GemDot is picking those up after this is merged.

File: python/tests/integration/arcticdb/test_arctic.py (hunk 9 above)
[the remark this answers is not in the document]
Comment (alexowens90) [reply python/tests/integration/arcticdb/test_arctic.py:1427]: This isn't trivial. We don't have a way to either generate the S3 object path from the `AtomKey`, or write arbitrary objects from the Python layer.

Comment (alexowens90) [reply python/tests/integration/arcticdb/test_arctic.py:1427]: Added a test for this and made a code change so that it correctly returns an `E_KEY_NOT_FOUND` error

File: cpp/arcticdb/version/python_bindings.cpp (hunk 8 above)
Comment (alexowens90) [reply cpp/arcticdb/version/python_bindings.cpp]: Changed

File: cpp/arcticdb/version/local_versioned_engine.cpp (hunk 7 above)
Comment (alexowens90) [reply cpp/arcticdb/version/local_versioned_engine.cpp:1107]: Yes, but the resulting code will have a `folly::collectAll` in it like `temp_batch_read_internal_direct`, rather than this messy loop-try-catch

File: cpp/arcticdb/version/local_versioned_engine.hpp (hunk 5 above)
Comment (alexowens90) [reply cpp/arcticdb/version/local_versioned_engine.hpp:282]: Yeh C++23, nice to know the patterns we're working around not existing are coming though.

File: cpp/arcticdb/entity/data_error.hpp (hunk 3 above)
Comment (alexowens90) [reply cpp/arcticdb/entity/data_error.hpp:19]: It looks more like the `VersionQueryType` I added. It would be better if all those classes were exposed to Python, instead of the `set_*` methods on `VersionQuery` right now, and we could just return one of those combining the `version_request_type` and `version_request_data` return parts right now.

File: cpp/arcticdb/version/local_versioned_engine.cpp (hunk 2 above)
Comment (alexowens90) [reply cpp/arcticdb/version/local_versioned_engine.cpp]: Its always set to true by `NativeVersionStore` right now

File: cpp/arcticdb/version/local_versioned_engine.cpp (hunk 1 above)
Comment (alexowens90) [reply cpp/arcticdb/version/local_versioned_engine.cpp:349]: Yes that's what it means

Comment (mehertz) [reply cpp/arcticdb/version/local_versioned_engine.cpp:349]: ...can we change the wording to make that clearer?

File: python/tests/integration/arcticdb/test_arctic.py (hunk 9 above)
[the remark this answers is not in the document]
Comment (mehertz) [reply python/tests/integration/arcticdb/test_arctic.py:1427]: That's a shame. We'll need a way to do this in the future otherwise we can't test error conditions where the data is just plain broken, rather than missing.

File: cpp/arcticdb/version/local_versioned_engine.cpp (hunk 2 above)
Comment (mehertz) [inline cpp/arcticdb/version/local_versioned_engine.cpp]: Shouldn't this check also be part of the non temp-batch read flow?

Comment (mehertz) [reply cpp/arcticdb/version/local_versioned_engine.cpp]: In fact, maybe this check should be just in `batch_read_internal`?

Comment (alexowens90) [reply cpp/arcticdb/version/local_versioned_engine.cpp]: Yeh I noticed this as well, have moved it

File: python/arcticdb/version_store/library.py (hunk 10 above)
[the remark this answers is not in the document]
Comment (mehertz) [reply python/arcticdb/version_store/library.py:879]: I'm not sure we need an alias to be honest. Makes it harder to read IMO.

**Comment by mehertz** [comment]
Closes #531
