### PR TITLE
Bugfix/1120/improve date range returned by get info for unordered and range indexed dataframes

### LINKED ISSUE #1120: get_description returns and incorrect row_range for unsorted datetime index data
### Describe the bug

It is possible to write data with an unsorted datetime index using validate_index=False.
If you write such data then lib.get_description on the symbol seems to have incorrect data, which looks like it is assuming the index is sorted.

### Steps/Code to Reproduce

```
arctic = adb.Arctic("lmdb://arcticdb_tests")
lib = arctic.get_library('get_desc', create_if_missing=True)
base3_df = pd.DataFrame(
    index=pd.DatetimeIndex(
        [datetime(2023, 11, 3), datetime(2023, 11, 1), datetime(2023, 11, 2)],
        name='date'
        ),
    data={'col': [3., 1., 2.]}
    )
sym3_unsorted = 'test_append3_unsorted'
lib.write(sym3_unsorted, base3_df, validate_index=False)
lib.get_description(sym3_unsorted)
```

### Expected Results

The row_range from the get_description is
```
date_range=(datetime.datetime(2023, 11, 3, 0, 0, tzinfo=datetime.timezone.utc), datetime.datetime(2023, 11, 2, 0, 0, tzinfo=datetime.timezone.utc))
```

Either return the correct row_range or nothing. Returning data that is incorrect but feasible is best avoided.

### OS, Python Version and ArcticDB Version

ArcticDB==4.1.0
Pandas==1.5.3
Python==3.10.12

### Backend storage used

LMDB

### Additional Context

Running on Jupyter colab.
Found independently based on a verbal bug report from an end user.

### PR DESCRIPTION
**Pull request by alexowens90**
Closes #1120 
`date_range` field of return values of `NativeVersionStore.get_info`, `Library.get_description`, and batch versions thereof now contain `NaT` if:

- the symbol is not timestamp indexed
- the symbol is timestamp indexed, but is known to be unsorted

### CODE REVIEW

File: cpp/arcticdb/version/version_core.cpp [hunk 1]
```diff
@@ -1214,13 +1217,17 @@ VersionedItem sort_merge_impl(
                 sk->unset_segment();
             }
             aggregator.commit();
+            pipeline_context->desc_->set_sorted(previous_sorted_value.has_value() ?
```
Comment (poodlewars) [inline cpp/arcticdb/version/version_core.cpp:1220]: The double ternary operator is a bit dense, explode out to `if`? Normally I'd put this kind of state machine logic with the `SortedValue` enum itself (it's also duplicated below).

File: python/tests/unit/arcticdb/version_store/test_parallel.py [hunk 2]
```diff
@@ -240,3 +242,48 @@ def test_datetimes_to_nats(lmdb_version_store):
...
+def test_compact_incomplete_prune_previous(lib_config, arg, append, version_store_factory):
+    lib = version_store_factory(prune_previous_version=lib_config)
+    lib.write("sym", pd.DataFrame({"col": [3]}, index=pd.DatetimeIndex([0])))
+    lib.append("sym", pd.DataFrame({"col": [4]}, index=pd.DatetimeIndex([1])), incomplete=True)
+
+    lib.compact_incomplete("sym", append, convert_int_to_float=False, prune_previous_version=arg)
+    assert lib.read_metadata("sym").version == 1
+
+    should_prune = lib_config if arg is None else arg
+    assert lib.has_symbol("sym", 0) == (not should_prune)
```
Comment (poodlewars) [inline python/tests/unit/arcticdb/version_store/test_parallel.py:259]: Not your test I know but why isn't this `!= should_prune` :(

**Review by poodlewars — APPROVED** [review]

File: cpp/arcticdb/pipeline/frame_utils.hpp [hunk 3]
```diff
@@ -13,6 +13,7 @@
 #include <arcticdb/pipeline/frame_slice.hpp>
 #include <arcticdb/entity/atom_key.hpp>
 #include <arcticdb/pipeline/input_tensor_frame.hpp>
+#include <arcticdb/pipeline/index_segment_reader.hpp>
```
[the remark this answers is not in the document]
Comment (alexowens90) [reply cpp/arcticdb/pipeline/frame_utils.hpp:16]: Error, will remove

File: python/tests/unit/arcticdb/version_store/test_parallel.py (hunk 2 above)
Comment (alexowens90) [reply python/tests/unit/arcticdb/version_store/test_parallel.py:259]: No idea, will change

File: cpp/arcticdb/version/version_core.cpp (hunk 1 above)
Comment (alexowens90) [reply cpp/arcticdb/version/version_core.cpp]: I accidentally committed to this branch for a PR that's gonna follow, so this has gone

File: cpp/arcticdb/pipeline/frame_utils.cpp [hunk 4]
```diff
@@ -148,4 +148,8 @@ std::pair<size_t, size_t> offset_and_row_count(const std::shared_ptr<pipelines::
     return std::make_pair(offset, row_count);
 }
 
+bool index_sorted_ascending(const std::shared_ptr<pipelines::InputTensorFrame>& frame) {
```
[the remark this answers is not in the document]
Comment (alexowens90) [reply cpp/arcticdb/pipeline/frame_utils.cpp:151]: Gone with `index_is_timeseries_and_sorted_ascending`

File: python/tests/unit/arcticdb/version_store/test_parallel.py (hunk 2 above)
Comment (alexowens90) [reply python/tests/unit/arcticdb/version_store/test_parallel.py:259]: I accidentally committed to this branch for a PR that's gonna follow, so this has gone
