### PR TITLE
Fixed aggregation on sparse grouping columns

### LINKED ISSUE #528: GroupBy and aggregation will not work with sparse columns
This is true if either the grouping column or any of the aggregation columns are sparse.

### PR DESCRIPTION
**Pull request by JohanMabille**
#### Reference Issues/PRs

Second part of #1007
Fixes #528 

#### What does this implement or fix?

- Fixes aggregations when grouping on a sparse column
- Adds C++ tests for this use case

#### Any other comments?

- Limitation: this requires to call `mark_absent_rows` on the grouping column, which is fragile. More generally, Column constructors should force the user to pass the size of the column for sparse columns.

#### Checklist

<details>
  <summary>
   Checklist for code changes...
  </summary>
 
 - [ ] Have you updated the relevant docstrings, documentation and copyright notice?
 - [ ] Is this contribution tested against [all ArcticDB's features](../docs/mkdocs/docs/technical/contributing.md)?
 - [ ] Do all exceptions introduced raise appropriate [error messages](https://docs.arcticdb.io/error_messages/)?
 - [ ] Are API changes highlighted in the PR description?
 - [ ] Is the PR labelled as enhancement or bug so it appears in autogenerated release notes?
</details>

### CODE REVIEW

File: cpp/arcticdb/processing/clause.cpp [hunk 1]
```diff
@@ -304,6 +304,19 @@ Composite<ProcessingUnit> AggregationClause::process(std::shared_ptr<Store> stor
...
+                                                bool is_sparse = col.column_->is_sparse();
+                                                using optional_iter_type = std::optional<decltype(input_data.bit_vector()->first())>;
+                                                optional_iter_type iter = std::nullopt;
+                                                size_t previous_value_index = 0;
+
+                                                if (is_sparse)
+                                                {
+                                                    iter = std::make_optional(input_data.bit_vector()->first());
+                                                    // We use 0 for the missing value group id
+                                                    next_group_id++;
```
Comment (jjerphan) [inline cpp/arcticdb/processing/clause.cpp:317]: This LGTM, but I cannot tell if this can invalidate some potential implicit invariant the aggregation clause or its tests might have been relying one.

**Review by jjerphan — COMMENTED** [review]
Thank you, @JohanMabille.

LGTM modulo a few comment.

Here are some comments. I think I would wait for someone else's approval before pursuing, because I do not have yet an entire comprehensive knowledge of `Column`'s internals.

Also, is there a non-regression test we could craft for https://github.com/man-group/ArcticDB/issues/528?

File: cpp/arcticdb/processing/clause.cpp [hunk 2]
```diff
@@ -304,6 +304,19 @@ Composite<ProcessingUnit> AggregationClause::process(std::shared_ptr<Store> stor
                                                 // 11.01 seconds with caching
                                                 // Not worth worrying about right now
                                                 robin_hood::unordered_flat_map<RawType, size_t> offset_to_group;
+
+                                                bool is_sparse = col.column_->is_sparse();
+                                                using optional_iter_type = std::optional<decltype(input_data.bit_vector()->first())>;
+                                                optional_iter_type iter = std::nullopt;
+                                                size_t previous_value_index = 0;
```
[the remark this answers is not in the document]
Comment (JohanMabille) [reply cpp/arcticdb/processing/clause.cpp:311]: Nope, `previous_value_index` is the index right after the last value set. Depending on the current iterator, it can be the index of a missing value, or of a value to set. I'm gonna change the logic so that it's always the index of the last value set.

File: cpp/arcticdb/processing/clause.cpp [hunk 3]
```diff
@@ -336,6 +358,11 @@ Composite<ProcessingUnit> AggregationClause::process(std::shared_ptr<Store> stor
                                                     }
                                                 }
 
+                                                # Marking all the last non-represented values as missing.
```
Comment (jjerphan) [inline cpp/arcticdb/processing/clause.cpp:361]: My bad.
```suggestion
                                                // Marking all the last non-represented values as missing.
```

**Review by jjerphan — APPROVED** [review]

File: cpp/arcticdb/processing/clause.cpp [hunk 4]
```diff
@@ -304,6 +304,20 @@ Composite<ProcessingUnit> AggregationClause::process(std::shared_ptr<Store> stor
                                                 // 11.01 seconds with caching
                                                 // Not worth worrying about right now
                                                 robin_hood::unordered_flat_map<RawType, size_t> offset_to_group;
+
+                                                bool is_sparse = col.column_->is_sparse();
```
Comment (willdealtry) [inline cpp/arcticdb/processing/clause.cpp:308]: Could be const, although I suspect it won't make a lot of difference

**Review by willdealtry — APPROVED** [review]

**Comment by JohanMabille** [comment]
Sparsy Sparsy Sparsy me
I'm a lucky kind of Column
