### PR TITLE
2113 using compact incomplete on a library with dynamic schema with a named index can result in an unreadable index

### LINKED ISSUE #2113: Using compact_incomplete on a library with dynamic schema with a named index can result in an unreadable index
### Describe the bug

When writing/appending with compact_incomplete, if some of the staged dataframes have a named index (e.g. df.index.name='date') this can result in an unreadable index, like:
``` bash
AssertionError: DataFrame.index are different

DataFrame.index values are different (50.0 %)
[left]:  DatetimeIndex(['2024-01-01', '2024-01-02'], dtype='datetime64[ns]', name='date', freq='D')
[right]: DatetimeIndex(['2024-01-01', 'NaT'], dtype='datetime64[ns]', name='date', freq=None)
At positional index 1, first diff: 2024-01-02T00:00:00.000000000 != NaT 
```

**This behavior reproduces only on libraries with dynamic schema because the different names are of the indexes make it so the static schema checks discard these segments.**

Here are the unit tests that reproduce this:
``` python
def test_parallel_write_dynamic_schema_named_index(lmdb_version_store_tiny_segment_dynamic):
    lib = lmdb_version_store_tiny_segment_dynamic
    sym = "test_parallel_append_dynamic_schema_named_index"
    df_0 = pd.DataFrame({"col_0": [0], "col_1": [0.5]}, index=pd.date_range("2024-01-01", periods=1))
    df_0.index.name = "date"
    df_1 = pd.DataFrame({"col_0": [1]}, index=pd.date_range("2024-01-02", periods=1))
    lib.write(sym, df_0, parallel=True)
    lib.write(sym, df_1, parallel=True)
    lib.compact_incomplete(sym, False, False)
    expected = pd.concat([df_0, df_1])
    expected.index.name = df_0.index.name
    received = lib.read(sym).data
    assert_frame_equal(expected, received)


def test_parallel_append_dynamic_schema_named_index(lmdb_version_store_tiny_segment_dynamic):
    lib = lmdb_version_store_tiny_segment_dynamic
    sym = "test_parallel_append_dynamic_schema_named_index"
    df_0 = pd.DataFrame({"col_0": [0], "col_1": [0.5]}, index=pd.date_range("2024-01-01", periods=1))
    df_0.index.name = "date"
    df_1 = pd.DataFrame({"col_0": [1]}, index=pd.date_range("2024-01-02", periods=1))
    lib.write(sym, df_0)
    lib.append(sym, df_1, incomplete=True)
    lib.compact_incomplete(sym, True, False)
    expected = pd.concat([df_0, df_1])
    expected.index.name = df_0.index.name
    received = lib.read(sym).data
    assert_frame_equal(expected, received)
```

For a standalone repro see below.

### Steps/Code to Reproduce

``` python
import pandas as pd
from arcticdb import Arctic, LibraryOptions
from pandas.testing import assert_frame_equal


def test_parallel_write_dynamic_schema_named_index(lib):
    sym = "test_parallel_append_dynamic_schema_named_index"
    df_0 = pd.DataFrame({"col_0": [0], "col_1": [0.5]}, index=pd.date_range("2024-01-01", periods=1))
    df_0.index.name = "date"
    df_1 = pd.DataFrame({"col_0": [1]}, index=pd.date_range("2024-01-02", periods=1))
    lib._nvs.write(sym, df_0, parallel=True)
    lib._nvs.write(sym, df_1, parallel=True)
    lib._nvs.compact_incomplete(sym, False, False)
    expected = pd.concat([df_0, df_1])
    expected.index.name = df_0.index.name
    received = lib.read(sym).data
    assert_frame_equal(expected, received)


def test_parallel_append_dynamic_schema_named_index(lib):
    sym = "test_parallel_append_dynamic_schema_named_index"
    df_0 = pd.DataFrame({"col_0": [0], "col_1": [0.5]}, index=pd.date_range("2024-01-01", periods=1))
    df_0.index.name = "date"
    df_1 = pd.DataFrame({"col_0": [1]}, index=pd.date_range("2024-01-02", periods=1))
    lib._nvs.write(sym, df_0)
    lib._nvs.append(sym, df_1, incomplete=True)
    lib._nvs.compact_incomplete(sym, True, False)
    expected = pd.concat([df_0, df_1])
    expected.index.name = df_0.index.name
    received = lib.read(sym).data
    assert_frame_equal(expected, received)


ac = Arctic("lmdb://test_parallel_dynamic_schema_named_index")
ac.delete_library("test_write")
ac.delete_library("test_append")
lib_write = ac.create_library("test_write", library_options=LibraryOptions(dynamic_schema=True))
lib_append = ac.create_library("test_append", library_options=LibraryOptions(dynamic_schema=True))

# Comment out the following line to run the append test
test_parallel_write_dynamic_schema_named_index(lib_write)
test_parallel_append_dynamic_schema_named_index(lib_append)
```

### Expected Results

The data frames should be the same and the index should be preserved.

### OS, Python Version and ArcticDB Version

Python: 3.10.15 (main, Sep  7 2024, 18:35:38) [GCC 13.2.0]
OS: Linux-5.15.167.4-microsoft-standard-WSL2-x86_64-with-glibc2.39
ArcticDB: 5.1.2

### Backend storage used

Any Storage

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by G-D-Petrov**
#### Reference Issues/PRs
Fixes #2113 

#### Checklist

<details>
  <summary>
   Checklist for code changes...
  </summary>
 
 - [ ] Have you updated the relevant docstrings, documentation and copyright notice?
 - [ ] Is this contribution tested against [all ArcticDB's features](../docs/mkdocs/docs/technical/contributing.md)?
 - [ ] Do all exceptions introduced raise appropriate [error messages](https://docs.arcticdb.io/error_messages/)?
 - [ ] Are API changes highlighted in the PR description?
 - [ ] Is the PR labelled as enhancement or bug so it appears in autogenerated release notes?
</details>

### CODE REVIEW

File: cpp/arcticdb/version/schema_checks.hpp [hunk 1]
```diff
@@ -86,6 +86,31 @@ inline void check_normalization_index_match(
...
 
+inline bool index_names_match(
+    const StreamDescriptor& df_in_store_descriptor,
+    const StreamDescriptor& new_df_descriptor
+) {
+    auto df_in_store_index_field_count = df_in_store_descriptor.index().type() == IndexDescriptor::Type::EMPTY ? 0 : df_in_store_descriptor.index().field_count();
+    auto new_df_field_index_count = new_df_descriptor.index().type() == IndexDescriptor::Type::EMPTY ? 0 : new_df_descriptor.index().field_count();
+
+    // If either index is empty, we consider them to match
+    if (df_in_store_index_field_count == 0 || new_df_field_index_count == 0) {
```
Comment (G-D-Petrov) [inline cpp/arcticdb/version/schema_checks.hpp:97]: This check is to accommodate the existing behavior around empty DFs and Series, both of which have essentially empty indexes, even though for series the types is RowCount, I think

**Comment by G-D-Petrov** [comment]
The benchmarks are reporting ~30% performance degradation on the FinalizeStagedData benchmarks:

| Change   | Before [d71a0bb5] <v5.2.0rc0~1>   | After [c1b389ee]    |   Ratio | Benchmark (Parameter)                                                      |
|----------|-----------------------------------|---------------------|---------|----------------------------------------------------------------------------|
| +        | 904M                              | 1.45G               |    1.6  | finalize_staged_data.FinalizeStagedData.peakmem_finalize_staged_data(1000) |
| +        | 1.88G                             | 2.73G               |    1.45 | finalize_staged_data.FinalizeStagedData.peakmem_finalize_staged_data(2000) |
| +        | 1.71±0s                           | 2.33±0s             |    1.36 | finalize_staged_data.FinalizeStagedData.time_finalize_staged_data(1000)    |
| +        | 3.49±0s                           | 4.66±0s             |    1.34 | finalize_staged_data.FinalizeStagedData.time_finalize_staged_data(2000)    |

I think that this is due to [the new check over all of the segments to make sure that the index names are the same](https://github.com/man-group/ArcticDB/pull/2116/files#diff-101f018db937d9932cd415402f8ff60559552ce72b63ff2efd3536bd83d828deR1085), which was not done before.

File: cpp/arcticdb/version/schema_checks.hpp [hunk 2]
```diff
@@ -86,6 +86,31 @@ inline void check_normalization_index_match(
     }
 }
 
+inline bool index_names_match(
```
Comment (vasil-pashov) [inline cpp/arcticdb/version/schema_checks.hpp:89]: Can we add schema_checks.cpp and add this there?

**Comment by vasil-pashov** [comment]
I think it's worth adding a test for `sort_and_finalize_staged_data` similar to the one for `finalize_staged_data` and the codepaths are slightly different

File: cpp/arcticdb/column_store/memory_segment_impl.cpp [hunk 3]
```diff
@@ -650,7 +650,7 @@ size_t SegmentInMemoryImpl::num_bytes() const {
 void SegmentInMemoryImpl::sort(const std::string& column_name) {
     init_column_map();
     auto idx = column_index(std::string_view(column_name));
-    user_input::check<ErrorCode::E_COLUMN_NOT_FOUND>(static_cast<bool>(idx), "Column {} not found in sort", column_name);
+    schema::check<ErrorCode::E_COLUMN_DOESNT_EXIST>(static_cast<bool>(idx), "Column {} not found in sort", column_name);
```
Comment (G-D-Petrov) [inline cpp/arcticdb/column_store/memory_segment_impl.cpp:653]: Note: I've changed this so it is more consistent with the other similar exceptions

File: python/tests/unit/arcticdb/version_store/test_parallel.py [hunk 4]
```diff
@@ -683,128 +904,305 @@ def test_parallel_append_dynamic_schema_missing_column(lmdb_version_store_tiny_s
...
+):
+    lib = lmdb_version_store_tiny_segment_dynamic
+    sym = "test_parallel_append_dynamic_schema_named_index"
+    df_0 = pd.DataFrame(
+        {"col_0": [0], "col_1": [0.5]}, index=pd.date_range("2024-01-01", periods=1)
+    )
+    df_0.index.name = "date"
+    df_1 = pd.DataFrame({"col_0": [1]}, index=pd.date_range("2024-01-02", periods=1))
+    lib.write(sym, df_0)
+    lib.append(sym, df_1, incomplete=True)
```
Comment (vasil-pashov) [inline python/tests/unit/arcticdb/version_store/test_parallel.py:946]: I think `append(...incomplete=True)` is the same as `write(...incomplete=True)`. Let's keep the test. It's questionable design decision that we allow it.

File: python/tests/unit/arcticdb/version_store/test_sort_merge.py [hunk 5]
```diff
@@ -868,3 +868,56 @@ def test_writing_wide_segment_over_sliced_data(self, lmdb_storage, lib_name):
         lib.sort_and_finalize_staged_data("sym", mode=StagedDataFinalizeMethod.WRITE)
 
         assert_frame_equal(lib.read("sym").data, df_1)
+
+
+@pytest.mark.parametrize("delete_staged_data_on_failure", [True, False])
+def test_sort_and_finalize_staged_data_write_dynamic_schema_named_index(
```
Comment (vasil-pashov) [inline python/tests/unit/arcticdb/version_store/test_sort_merge.py:874]: nit: Can't this be parametrized by mode=[StagedDataFinalizeMethod.WRITE,, StagedDataFinalizeMethod.APPEND] as well to avoid repetition?

File: cpp/arcticdb/version/schema_checks.cpp [hunk 6]
```diff
@@ -0,0 +1,154 @@
...
+        }
+    }
+}
+
+bool index_names_match(
+    const StreamDescriptor& df_in_store_descriptor,
+    const StreamDescriptor& new_df_descriptor
+) {
+    auto df_in_store_index_field_count = df_in_store_descriptor.index().type() == IndexDescriptor::Type::EMPTY ? 0 : df_in_store_descriptor.index().field_count();
+    auto new_df_field_index_count = new_df_descriptor.index().type() == IndexDescriptor::Type::EMPTY ? 0 : new_df_descriptor.index().field_count();
```
Comment (alexowens90) [inline cpp/arcticdb/version/schema_checks.cpp:79]: Won't `field_count()` be `0` for empty index types anyway?

File: cpp/arcticdb/version/schema_checks.cpp [hunk 7]
```diff
@@ -0,0 +1,154 @@
...
+
+    // If either index is empty, we consider them to match
+    if (df_in_store_index_field_count == 0 || new_df_field_index_count == 0) {
+        return true;
+    }
```
Comment (alexowens90) [inline cpp/arcticdb/version/schema_checks.cpp:84]: The field count will also be `0` for range indexes. I just checked and range indexes can have a name in Pandas, but I don't know if we persist them, can you check?

**Review by alexowens90 — APPROVED** [review]
