### PR TITLE
Bugfix 1507+1509: dynamic schema different index append fixes

### LINKED ISSUE #1507: Dynamic schema can append rowrange to datetime index leading to datacorruption
### Describe the bug

When dynamic schema is enabled and the symbol contains empty dataframe it is possible to append a rowrange index to the symbol. This should be forbidden since the indexes are not matching. The append changes the index type to be rowrange, but still it is possible to append datetime to that as well leading to a data corruption.

### Steps/Code to Reproduce

```python
import arcticdb
import numpy as np
import pandas as pd

# 4.4.0
print(arcticdb.__version__)

ac = arcticdb.Arctic("lmdb://test")
opts = arcticdb.LibraryOptions(dynamic_schema=True)
lib = ac.get_library("test", create_if_missing=True, library_options=opts)

lib.write("test_dyn", pd.DataFrame({"a": [], dtype="float64"}))
assert lib.read("test_dyn").data.index.equals(pd.DatetimeIndex([]))

# This should not be allowed
lib.append("test_dyn", pd.DataFrame({"a": [1.0]}, pd.RangeIndex(start=0, stop=1, step=1)))
# The index appears to be changed
assert lib.read("test_dyn").data.index.equals(pd.RangeIndex(start=0, stop=1, step=1))
# The output looks ok even though the index is messed up
#    a
# 0  1
print(lib.read("test_dyn").data)


# Even though the index appears to be changed the following will throw:
# lib.append("test_dyn", pd.DataFrame({"a": [1.0]}, pd.RangeIndex(start=1, stop=2, step=1)))

# Appending datetime to this is allowed only if validate index is false
lib.append("test_dyn", pd.DatetimeIndex(["01/01/2024"]), validate_index=False)

# The data is corrupted
#                         index
# 1                         NaT
# 682406825570164596 2024-01-01
```

### Expected Results

There are two cases:
1. The empty index feature is enabled (#1429, #1475)
Anything could be appended to symbol containing an empty dataframe. The type of the index is determined at the time of first append (or update). After the type of the index is determined index mixing indexes should not be allowed.

2. The empty index feature is disabled
The index is determined at write time. In case of Pandas 2 it is DatetimeIndex([]) for all empty DataFrames (in case of Pandas 1 it is not so consistent refer to test_empty_column_type.py for the expected behavior). Appending to a symbol containing empty dataframe is allowed only if the indexes are matching.

### OS, Python Version and ArcticDB Version

Python: 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
OS: Windows-10-10.0.22631-SP0
ArcticDB: 4.4.0
Numpy: 1.26.3
Pandas: 2.1.4

### Backend storage used

_No response_

### Additional Context

_No response_

### LINKED ISSUE #1509: Dynamic schema allows appending non-matching RangeIndexes
### Describe the bug

When dynamic schema is enabled it is possible to append dataframe with ranged index to symbol even if the ranges are not matching. This makes it possible to
1. Append ranged index with start different than the stop of the symbol
2. Append ranged index with step different than the step of the symbol
Both actions change the index even for the old rows and are forbidden with static_schema.

### Steps/Code to Reproduce

```python
>>> import arcticdb
>>> import pandas as pd
>>> import numpy as np
>>> ac = arcticdb.Arctic("lmdb://test")
>>> opts = arcticdb.LibraryOptions(dynamic_schema=True)
>>> lib = ac.get_library("test", create_if_missing=True, library_options=opts)
>>> lib.write("test", pd.DataFrame({"a": [1, 2, 3]}))
VersionedItem(symbol='test', library='test', data=n/a, version=0, metadata=None, host='LMDB(path=...test)', timestamp=1713515824376569000)
>>> lib.read("test").data
   a
0  1
1  2
2  3
>>> lib.append("test", pd.DataFrame({"a": [1]}, pd.RangeIndex(start=5, stop=6, step=1)))
VersionedItem(symbol='test', library='test', data=n/a, version=1, metadata=None, host='LMDB(path=...test)', timestamp=1713515904432580000)
>>> lib.read("test").data
   a
5  1
6  2
7  3
8  1
>>> lib.append("test", pd.DataFrame({"a": [1]}, pd.RangeIndex(start=5, stop=6, step=10)))
VersionedItem(symbol='test', library='test', data=n/a, version=6, metadata=None, host='LMDB(path=...test)', timestamp=1713517240251682100)
>>> lib.read("test").data
    a
5   1
15  2
25  3
35  1
45  1
```

### Expected Results

Do not allow appending RangeIndex-ed dataframes if the ranges are not matching.

### OS, Python Version and ArcticDB Version

Python: 3.10.11 (tags/v3.10.11:7d4cc5a, Apr 5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
OS: Windows-10-10.0.22631-SP0
ArcticDB: 4.4.0
Numpy: 1.26.3
Pandas: 2.1.4

### Backend storage used

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by alexowens90**
Closes #1507 
Closes #1509

While fixing, noticed that the added test `test_append_range_index_from_zero` would also not have passed, so fixed this too.

### CODE REVIEW

File: cpp/arcticdb/python/normalization_checks.cpp [hunk 1]
```diff
@@ -122,17 +122,15 @@ void update_rowcount_normalization_data(
...
-                    "The appending data has a RangeIndex.start={} that is not contiguous with the {}"
-                    "stop ({}) of",
-                    error_suffix,
-                    new_start,
-                    stop
-                );
-            }
+            auto stop = old_index->start() + old_length * old_index->step();
+            normalization::check<ErrorCode::E_INCOMPATIBLE_INDEX>(
+                new_start == stop || (new_start == 0 && new_index->step() == 1),
```
Comment (vasil-pashov) [inline cpp/arcticdb/python/normalization_checks.cpp:127]: is this going to allow something like this to happen
     a
0   0
1   1
2   2

Append index (0, 1, 2)

     a
0   0
1   1
2   2
0   3
1   4
2   5

Or is there some other check preventing it?

Comment (alexowens90) [reply cpp/arcticdb/python/normalization_checks.cpp:127]: We have to allow appending index `[0, 1, 2` to index `[0, 1, 2]`, otherwise our default behaviour when you don't provide an index won't work. We only store the start and step though, so it will come out as:
```
0 0
1 1
2 2
3 3
4 4
5 5
```

**Review by vasil-pashov — APPROVED** [review]
