### PR TITLE
Bugfix/935/match pandas behviour when aggregating columns with nans

### LINKED ISSUE #935: QueryBuilder Aggregators do not match Pandas for data with NaNs
### Describe the bug

Using the following data set

image

I applied aggregators in arctic QueryBuilder and Pandas. The results are that arctic matched pandas without NaNs and for min/max, but sum and mean return NaN if there are any NaNs in the data in arctic, where pandas skips them

image

image

### Steps/Code to Reproduce

```
import os
import numpy as np
import pandas as pd
import numpy as np
import random
from arcticdb import Arctic, QueryBuilder
from arcticdb.util.test import random_strings_of_length

arctic = Arctic("lmdb://arcticdb_demo")

if 'sample' not in arctic.list_libraries():
    arctic.create_library('sample')
lib = arctic.get_library('sample')

test_dict = {
    'labels': ['red', 'blue', 'red', 'blue', 'red', 'blue'],
    'numbers': [1.0, 2.0, 3.0, 4.0, 5.0, 6.0],
    'numbers_nans': [11.0, np.nan, 13.0, 14.0, np.nan, 16.0],
    'numbers_nans2': [11.0, np.nan, 13.0, np.nan, 15.0, np.nan],
}
test_df = pd.DataFrame(test_dict)
test_df

test_sym = "test_qb_nans"
lib.write(test_sym, test_df)

agg_list = ["min", "max", "sum", "mean"]

all_agg_df = []
all_pandas_agg_df = []
for agg in agg_list:
    q = QueryBuilder()
    q = q.groupby("labels").agg({"numbers": agg, "numbers_nans": agg, "numbers_nans2": agg})
    agg_df = lib.read(test_sym, query_builder=q).data.sort_index()
    agg_df.columns = pd.MultiIndex.from_product([[f"{agg}: artic"], agg_df.columns])
    pandas_agg_df = test_df.groupby("labels").agg(agg).sort_index()
    pandas_agg_df.columns = pd.MultiIndex.from_product([[f"{agg}: pandas"], pandas_agg_df.columns])
    print(agg_df)
    print(pandas_agg_df)
    all_agg_df.append(agg_df)
    all_pandas_agg_df.append(pandas_agg_df)

pd.concat(all_agg_df, axis=1)

pd.concat(all_pandas_agg_df, axis=1)
```

### Expected Results

Pandas gives the expected results

### OS, Python Version and ArcticDB Version

Python: 3.8 using Man pegasus next running on jupyterhub

### Backend storage used

LMDB

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by alexowens90**
Fixes #935 

Also addresses two of the bullet points from #1439:

- AggregationClause::process x2
- aggregation.cpp all finalize methods

### CODE REVIEW

File: cpp/arcticdb/processing/aggregation.cpp [hunk 1]
```diff
@@ -302,36 +306,32 @@ namespace
...
-                });
-            } else {
-                details::visit_type(*data_type_, [&aggregated_, &data_type_, &res, output_column_name, unique_values] (auto col_tag) {
-                    using RawType = typename decltype(col_tag)::DataTypeTag::raw_type;
-                    auto col = std::make_shared<Column>(make_scalar_type(data_type_.value()), unique_values, true, false);
-                    const auto* in_ptr =  reinterpret_cast<const MaybeValue<RawType, T>*>(aggregated_.data());
-                    auto out_ptr = reinterpret_cast<RawType*>(col->ptr());
-                    for(auto i = 0u; i < unique_values; ++i, ++in_ptr, ++out_ptr) {
-                        *out_ptr = in_ptr->value_;
+                    for (auto it = column_data.begin<dynamic_schema_tdt>(); it != column_data.end<dynamic_schema_tdt>(); ++it, ++in_ptr) {
```
Comment (willdealtry) [inline cpp/arcticdb/processing/aggregation.cpp:324]: Don't hugely mind but snake case type is not the normal pattern. Is there a reason why this diverges?

**Review by DrNickClarke — APPROVED** [review]

File: cpp/arcticdb/processing/aggregation.cpp (hunk 1 above)
Comment (alexowens90) [reply cpp/arcticdb/processing/aggregation.cpp:324]: Nope, will change
