### PR TITLE
Bugfix/1518/get description date range incorrect after delete data in range

### LINKED ISSUE #1518: index date_range is sometimes incorrect after delete_data_in_range()
### Describe the bug

After delete_data_in_range() the data is correct but the date_range in get_description() can be wrong. See the repro code for details.

### Steps/Code to Reproduce
```
from datetime import datetime, timedelta
import numpy as np
import pandas as pd
import arcticdb as adb

arctic = adb.Arctic("lmdb://arcticdb_bugs")
lib = arctic.get_library("test_of_arctic_date", create_if_missing=True)
sym = "stock"

base_start_date = datetime(1990, 1, 1)
base_end_date = datetime(2020, 1, 1)
cols = ["open", "high", "low", "close", "vwap", "volume"]
sym = "stock"
base_index = pd.date_range(base_start_date, base_end_date, inclusive="left")
base_df = pd.DataFrame(
    np.random.randn(len(base_index), len(cols)), index=base_index, columns=cols
)
lib.write(sym, base_df)

# after the write the data_range in get_description and read_index are correct
lib.get_description(sym).date_range
lib._nvs.read_index(sym)

lib.delete_data_in_range(sym, (pd.Timestamp("2019-12-30"), pd.Timestamp("2019-12-31")))

# after the delete_data_in_range the data_range in get_description and read_index are incorrect
# the end data is 30-12-2019, should be 29-12-2019
lib.get_description("stock").date_range
lib._nvs.read_index(sym)
# the data is correct
lib.read(sym).data
```

### Expected Results

date_range should be correct after delete_data_in_range()

### OS, Python Version and ArcticDB Version

Python: 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
OS: Linux-5.15.146.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
ArcticDB: 4.4.1

### Backend storage used

LMDB

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by alexowens90**
Closes #1518

### CODE REVIEW

**Review by willdealtry — APPROVED** [review]

File: cpp/arcticdb/version/local_versioned_engine.cpp [hunk 1]
```diff
@@ -363,53 +363,33 @@ folly::Future<DescriptorItem> LocalVersionedEngine::get_descriptor(
...
+            seg.metadata()->UnpackTo(&(*tsd));
+        }
+        std::optional<timestamp> start_index;
+        std::optional<timestamp> end_index;
+        if (seg.row_count() > 0) {
+            const auto& start_index_column = seg.column(position_t(index::Fields::start_index));
+            details::visit_type(start_index_column.type().data_type(), [&start_index_column, &start_index](auto column_desc_tag) {
+                using type_info = ScalarTypeInfo<decltype(column_desc_tag)>;
+                if constexpr (is_time_type(type_info::data_type)) {
+                    start_index = start_index_column.template scalar_at<timestamp>(0);
```
Comment (willdealtry) [inline cpp/arcticdb/version/local_versioned_engine.cpp:379]: Was there a reason not to use start_value_for_segment and end_value_for_segment from index.hpp?

Comment (alexowens90) [reply cpp/arcticdb/version/local_versioned_engine.cpp:379]: This is an index key, not a data key
