### PR TITLE
Bugfix 1035

### LINKED ISSUE #1035: Using QueryBuilder on grouping column with floats fails on Linux Conda
### Describe the bug

Using QueryBuilder on grouping column with floats fails on Linux Conda.
The bigger problem is that this doesn't reproduce on all versions.
It has been experienced only on Linux Conda on self-hosted ec2 runners and only on release builds.

Can be reproduced with the following test - test_group_on_float_column_with_nans

### Steps/Code to Reproduce

``` python 
ac = Arctic("lmdb://test_dir")
ac.create_library("some_lib")
lib = ac["some_lib"]
sym = "test_group_on_float_column_with_nans"
df = pd.DataFrame({"grouping_column": [1.0, 2.0, np.nan, 1.0, 2.0, 2.0], "agg_column": [1, 2, 3, 4, 5, 6]})
lib.write(sym, df)
expected = df.groupby("grouping_column").agg({"agg_column": "sum"})
q = QueryBuilder()
q = q.groupby("grouping_column").agg({"agg_column": "sum"})
received = lib.read(sym, query_builder=q).data
received.sort_index(inplace=True)
assert_frame_equal(expected, received)
```

### Expected Results

The columns are correctly grouped like this:

1.0                       5
2.0                      13

### OS, Python Version and ArcticDB Version

Python: 3.10.13 | packaged by conda-forge | (main, Oct 26 2023, 18:07:37) [GCC 12.3.0]
OS: Linux-6.2.0-1015-aws-x86_64-with-glibc2.35
ArcticDB: 1.4.1.dev0

### Backend storage used

LMDB

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by alexowens90**
Closes #1035 

There is still an issue with non-deterministic hashing in the linux conda build, #1268 opened to investigate this further.
In addition:

- We were previously dynamically linking `xxhash` in the conda builds, despite using macros designed for static linking. Now it is linked in statically.
- We were not pinning the `xxhash` version in the conda builds, and so were on the latest version `0.8.2`. This is now pinned to `0.8.2`. This pin will presumably need to be replicated in the feedstock.
- We were using `xxhash.c` and `xxhash.h` files copied from version `0.6.5` of the project. We now pull in this dependency using `vcpkg`, pinned to version `0.8.2`.
- https://fastcompression.blogspot.com/2018/03/xxhash-for-small-keys-impressive-power.html claims that for small keys, if the size argument to the `xxhash` hashing functions is a compile-time constant, then performance improvements can be observed, so an overload of `hash` was added to do this. This is the method used for hashing aggregations, where the keys are at most 8 bytes long for non-string columns.

### CODE REVIEW

**Review by willdealtry — APPROVED** [review]

File: cpp/arcticdb/util/hash.hpp [hunk 1]
```diff
@@ -10,31 +10,42 @@
...
 using HashedValue = XXH64_hash_t;
 constexpr std::size_t DEFAULT_SEED = 0x42;
 
 template<class T, std::size_t seed = DEFAULT_SEED>
-HashedValue hash(T *d, std::size_t count = 1) {
+HashedValue hash(T *d, std::size_t count) {
     return XXH64(reinterpret_cast<const void *>(d), count * sizeof(T), seed);
 }
 
+// size argument to XXH64 being compile-time constant improves performance
```
Comment (jjerphan) [inline cpp/arcticdb/util/hash.hpp:43]:
```suggestion
// This is the specialization of hash for `count = 1` size having the
// `size` argument to `XXH64` being compile-time constant improves performance.
```

File: python/tests/unit/arcticdb/version_store/test_aggregation.py [hunk 2]
```diff
@@ -22,10 +22,7 @@
 from hypothesis import assume, given, settings
 from hypothesis.extra.pandas import column, data_frames, range_indexes
 
-from tests.util.mark import xfail_on_linux_conda
```
Comment (jjerphan) [inline python/tests/unit/arcticdb/version_store/test_aggregation.py:25]: `xfail_on_linux_conda` can now be removed since it is not used anymore.

File: cpp/arcticdb/CMakeLists.txt [hunk 3]
```diff
@@ -524,12 +528,13 @@ endif()
 # on their origin (i.e. vendored source or packages on conda-forge).
 if(${ARCTICDB_USING_CONDA})
 
-    # We must use dynamic libraries.
+    # We must use dynamic libraries, except for xxHash, which must be statically linked.
+    # In non-conda builds, we inline the functions so it does not need linking at all.
```
Comment (jjerphan) [inline cpp/arcticdb/CMakeLists.txt:532]:
```suggestion
    # For all builds but linux conda's, we inline the functions so that
    # xxhash does not need linking at all.
```

File: cpp/arcticdb/CMakeLists.txt [hunk 4]
```diff
@@ -90,6 +90,10 @@ else()
     list(REMOVE_ITEM NEW_FOLLY_DEPS "/usr/local/opt/openssl/include" )
     set_target_properties(Folly::folly_deps PROPERTIES INTERFACE_INCLUDE_DIRECTORIES "${NEW_FOLLY_DEPS}")
 
+    add_library(xxHash STATIC IMPORTED)
+    set_target_properties(xxHash PROPERTIES IMPORTED_LOCATION ${xxHash_LIBRARY})
+    set_target_properties(xxHash PROPERTIES INTERFACE_INCLUDE_DIRECTORIES ${xxHash_INCLUDE_DIR})
```
Comment (jjerphan) [inline cpp/arcticdb/CMakeLists.txt:95]: Shouldn't this be done for conda packages and for wheels (i.e. independently from `ARCTICDB_USING_CONDA`)?

File: cpp/arcticdb/CMakeLists.txt [hunk 5]
```diff
@@ -524,12 +528,13 @@ endif()
...
-    # We must use dynamic libraries.
+    # We must use dynamic libraries, except for xxHash, which must be statically linked.
+    # In non-conda builds, we inline the functions so it does not need linking at all.
     list (APPEND arcticdb_core_libraries
-        xxHash::xxHash
         pcre
         msgpack-c
         ${LMDB_LIBRARIES}
+        xxHash
     )
```
Comment (jjerphan) [inline cpp/arcticdb/CMakeLists.txt:538]: Was this change needed because of vcpkg's distribution?

File: cpp/arcticdb/CMakeLists.txt [hunk 6]
```diff
@@ -524,12 +528,13 @@ endif()
 # on their origin (i.e. vendored source or packages on conda-forge).
 if(${ARCTICDB_USING_CONDA})
 
-    # We must use dynamic libraries.
+    # We must use dynamic libraries, except for xxHash, which must be statically linked.
```
Comment (jjerphan) [inline cpp/arcticdb/CMakeLists.txt:531]:
```suggestion
    # We must use dynamic libraries, except for xxHash, which must be statically linked
    # since `XXH64_state_t` which is used ArcticDB is only available for static linkage.
```

File: cpp/arcticdb/CMakeLists.txt (hunk 4 above)
Comment (alexowens90) [reply cpp/arcticdb/CMakeLists.txt:95]: `xxHash` isn't a target in the vcpkg build, so this won't work

File: cpp/arcticdb/CMakeLists.txt (hunk 3 above)
Comment (alexowens90) [reply cpp/arcticdb/CMakeLists.txt]: Rephrased

File: cpp/arcticdb/CMakeLists.txt (hunk 5 above)
Comment (alexowens90) [reply cpp/arcticdb/CMakeLists.txt]: No, you can use either, I'd just removed it and then put it back with the alternative name. Reverted now.

File: cpp/arcticdb/CMakeLists.txt (hunk 6 above)
Comment (alexowens90) [reply cpp/arcticdb/CMakeLists.txt:532]: Rephrased
