### PR TITLE
Detailed error in case of S3's libcurl network failure

### LINKED ISSUE #880: libcurl error when executing requests across large numbers of Arctic and Library instances in python
### Describe the bug

libcurl error when executing requests across large numbers of Arctic and Library instances in python

### Steps/Code to Reproduce

```python
aas = []
for i in count():
    print(i)
    arctic = Arctic(f's3://s3.{region}.amazonaws.com:{bucket_name}?aws_auth=true')
    aas.append(arctic)
    lib = arctic.get_library('bench')
    lib.head('data')
```

Fails after 461 instances on a 16Gig Intel laptop, running WSL with:
```
[2023-09-21 15:12:05.623] [arcticdb] [error] Got unexpected error: '99' : curlCode: 6, Couldn't resolve host name
---------------------------------------------------------------------------
InternalException                         Traceback (most recent call last)
Cell In[16], line 5
      3 arctic = Arctic(f's3://s3.{region}.amazonaws.com:{bucket_name}?aws_auth=true')
      4 aas.append(arctic)
----> 5 lib = arctic.get_library('bench')
      6 lib.head('data')

File ~/miniforge3/envs/arcticdb/lib/python3.11/site-packages/arcticdb/arctic.py:231, in Arctic.get_library(self, name, create_if_missing, library_options)
    227     raise ArcticInvalidApiUsageException(
    228         "In get_library, library_options must be falsey if create_if_missing is falsey"
    229     )
    230 try:
--> 231     lib = self[name]
    232     if create_if_missing and library_options:
    233         if library_options.encoding_version is None:

File ~/miniforge3/envs/arcticdb/lib/python3.11/site-packages/arcticdb/arctic.py:177, in Arctic.__getitem__(self, name)
    174 if already_open:
    175     return already_open
--> 177 if not self._library_manager.has_library(name):
    178     raise LibraryNotFound(name)
    180 storage_override = self._library_adapter.get_storage_override()

InternalException: arcticdb::storage::s3::detail::UnexpectedS3ErrorException(std::exception)
```
In another environment (AWS k8s container) we saw an error after ~345 instances of Arctic with the following error:

```
InternalException: arcticdb::storage::s3::detail::UnexpectedS3ErrorException(std::exception)

20230919 16:17:35.490339 2777 E arcticdb.storage | Got unexpected error: '99' : curlCode: 35, SSL connect error
```

### Expected Results

No error until memory is exhausted.

### OS, Python Version and ArcticDB Version

Python: 3.11.5 | packaged by conda-forge | (main, Aug 27 2023, 03:34:09) [GCC 12.3.0]
OS: Linux-4.4.0-19041-Microsoft-x86_64-with-glibc2.31
ArcticDB: 3.0.0

### Backend storage used

AWS S3
### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by IvoDD**
#### Reference Issues/PRs
Closes #880

#### What does this implement or fix?
Previously on network connection failures we'd get an error message like `Got unexpected error: '99' : curlCode: 6, Couldn't resolve host name`.

Now we explain that this can be either caused by connection issues or by exhausted open sockets and suggests increasing `ulimit -n`.

#### Any other comments?
Didn't add a unit test since it's hard to reproduce in a unit test environment. So I tested locally as follows:
```
$ cat many_arctic.py
from arcticdb import Arctic

aas = []

for i in range(1000):
    print(i)
    arctic = Arctic("s3://172.22.107.88:test?port=9000&access=<ACCESS>&secret=<SECRET>")
    aas.append(arctic)
    arctic.has_library(f"lib_{i}")
$ ulimit -n 50
$ python many_arctic.py
0
1
2
3
4
5
6
7
8
[2024-01-23 16:35:53.717] [arcticdb] [error] Got an unexpected network error: curlCode: 7, Couldn't connect to server.
This could be due to a connectivity issue or exhausted open sockets. In case socket file descriptors are exhausted, consider increasing `ulimit -n`.
Traceback (most recent call last):
  File "/home/ivo/source/ArcticDB/python/many_arctic.py", line 9, in <module>
    arctic.has_library(f"lib_{i}")
  File "/home/ivo/source/ArcticDB/python/arcticdb/arctic.py", line 345, in has_library
    return self._library_manager.has_library(self._library_adapter.get_name_for_library_manager(name))
arcticdb_ext.exceptions.InternalException: arcticdb::storage::s3::detail::UnexpectedS3ErrorException(Got an unexpected network error: curlCode: 7, Couldn't connect to server. This could be due to a connectivity issue or too many open Arctic instances. Having more than one open Arctic instance is not advised, you should reuse them. If you absolutely need many open Arctic instances, consider increasing `ulimit -n`.)
```

#### Checklist

<details>
  <summary>
   Checklist for code changes...
  </summary>
 
 - [ ] Have you updated the relevant docstrings, documentation and copyright notice?
 - [ ] Is this contribution tested against [all ArcticDB's features](../docs/mkdocs/docs/technical/contributing.md)?
 - [ ] Do all exceptions introduced raise appropriate [error messages](https://docs.arcticdb.io/error_messages/)?
 - [ ] Are API changes highlighted in the PR description?
 - [ ] Is the PR labelled as enhancement or bug so it appears in autogenerated release notes?
</details>

### CODE REVIEW

File: cpp/arcticdb/storage/s3/detail-inl.hpp [hunk 1]
```diff
@@ -125,6 +125,26 @@ namespace s3 {
...
+                                         err.GetMessage().c_str());
+                }
+                else {
+                    log::storage().error("Got unexpected error: '{}' {}: {}",
+                                         int(err.GetErrorType()),
+                                         err.GetExceptionName().c_str(),
+                                         err.GetMessage().c_str());
+                }
+
+                throw UnexpectedS3ErrorException{};
```
Comment (poodlewars) [inline cpp/arcticdb/storage/s3/detail-inl.hpp:144]: Does this bubble up to the Python layer? How does it look there?

I wonder if it is worth including more information in the exception itself, since in Jupyterhub our logging isn't shown properly.

**Review by poodlewars — APPROVED** [review]

File: cpp/arcticdb/storage/s3/detail-inl.hpp [hunk 2]
```diff
@@ -125,6 +125,26 @@ namespace s3 {
                    || err == Aws::S3::S3Errors::RESOURCE_NOT_FOUND;
         }
 
+        inline void raise_if_unexpected_error(const Aws::S3::S3Error& err){
+            if (!is_expected_error_type(err.GetErrorType())) {
+                // We log a more detailed error explanation in case of NETWORK_CONNECTION errors to remedy #880.
+                if (err.GetErrorType() == Aws::S3::S3Errors::NETWORK_CONNECTION){
+                    log::storage().error("Got an unexpected network error: {}. "
+                                         "This could be due to a connectivity issue or exhausted open sockets. "
+                                         "In case socket file descriptors are exhausted, consider increasing `ulimit -n`.",
```
Comment (poodlewars) [inline cpp/arcticdb/storage/s3/detail-inl.hpp:134]: Ah I misremembered the message. We should, like @alexowens90 said, suggest creating fewer `Arctic` objects in the first instance (the system works best with only one per connection URI live in memory at a time).
