### PR TITLE
Bugfix/1080/batch read with snapshots fix port

### LINKED ISSUE #1080: Port `batch_read` with snapshots fix to `4.0.x` branch

### PR DESCRIPTION
**Pull request by alexowens90**
Fixes #1080

### CODE REVIEW

File: cpp/arcticdb/async/task_scheduler.hpp [hunk 1]
```diff
@@ -102,8 +104,7 @@ struct SchedulerWrapper : public SchedulerType {
 };
 
 inline int64_t get_cgroup_value(const std::string& cgroup_file) {
-    const auto path = std::filesystem::path{fmt::format("/sys/fs/cgroup/{}",cgroup_file)};
-    if(std::filesystem::exists(path)){
+    if(const auto path = std::filesystem::path{fmt::format("/sys/fs/cgroup/{}",cgroup_file)}; std::filesystem::exists(path)){
```
Comment (vasil-pashov) [inline cpp/arcticdb/async/task_scheduler.hpp:107]: `std::filesystem::path` has an `operator/` which should be used for concatenating paths instead of manual formatting.

File: cpp/arcticdb/async/task_scheduler.hpp [hunk 2]
```diff
@@ -156,22 +155,27 @@ class TaskScheduler {
...
+        util::check(cpu_thread_count_ > 0 && io_thread_count_ > 0, "Zero IO or CPU threads: {} {}", io_thread_count_, cpu_thread_count_);
         ARCTICDB_RUNTIME_DEBUG(log::schedule(), "Task scheduler created with {:d} {:d}", cpu_thread_count_, io_thread_count_);
     }
 
     ~TaskScheduler() = default;
 
     template<class Task>
-    auto submit_cpu_task(Task &&task) {
+    auto submit_cpu_task(Task &&t) {
+        auto task = std::forward<decltype(t)>(t);
```
Comment (vasil-pashov) [inline cpp/arcticdb/async/task_scheduler.hpp:166]: Why do we need to do this? Why not return `cpu_exec_.addFuture(std::move(t));`?

File: cpp/arcticdb/entity/types.hpp [hunk 3]
```diff
@@ -124,7 +124,7 @@ enum class ValueType : uint8_t {
     // For instance, Pandas empty series whose types has not been specified is mapping to EMPTY.
     // When data is appended, the column type is inferred from the data and the column is promoted to the inferred type.
     EMPTY = 13,
-    COUNT // Not a real value type, should not be added to proto descriptor. Used to count the number of items in the enum
+    COUNT = 14 // Not a real value type, should not be added to proto descriptor. Used to count the number of items in the enum
```
Comment (vasil-pashov) [inline cpp/arcticdb/entity/types.hpp:127]: NIT: I think this is a bit error prone. When adding new type people have to add value and update the count. Usually the count is left without a value so that it auto-increments

File: cpp/arcticdb/log/log.cpp [hunk 4]
```diff
@@ -65,6 +65,14 @@ spdlog::logger &message() {
     return Loggers::instance()->message();
 }
 
+spdlog::logger &symbol() {
```
Comment (vasil-pashov) [inline cpp/arcticdb/log/log.cpp:68]: [[nodiscard]]?

**Review by vasil-pashov — APPROVED** [review]
