### PR TITLE
Bugfix 1278: filtering and projections on sparse columns

### LINKED ISSUE #1278: Filtering does not work on sparse columns
See also https://github.com/man-group/arcticdb-man/issues/82

### PR DESCRIPTION
**Pull request by alexowens90**
Fixes #1278 and https://github.com/man-group/arcticdb-man/issues/82

Makes filtering and projections work on sparse columns.

### CODE REVIEW

File: cpp/arcticdb/column_store/column.hpp [hunk 1]
```diff
@@ -603,35 +611,36 @@ class Column {
         internal::check<ErrorCode::E_ASSERTION_FAILURE>(!is_sparse(),
                                                         "Column::search_sorted not supported with sparse columns");
         std::optional<size_t> res;
-        type().visit_tag([this, &res, val, from_right](auto type_desc_tag){
-            using TDT = decltype(type_desc_tag);
-            using RawType = typename TDT::DataTypeTag::raw_type;
-            if constexpr(std::is_same_v<T, RawType>) {
+        auto column_data = data();
+        details::visit_type(type().data_type(), [this, &res, &column_data, val, from_right](auto type_desc_tag) {
```
Comment (vasil-pashov) [inline cpp/arcticdb/column_store/column.hpp:615]: I guess the parameter is no longer type_descriptor_tag but data_type_tag

File: cpp/arcticdb/column_store/column.hpp [hunk 2]
```diff
@@ -670,7 +679,22 @@ class Column {
...
     static void for_each(const Column& input_column, functor&& f) {
         auto input_data = input_column.data();
-        std::for_each(input_data.cbegin<input_tdt>(), input_data.cend<input_tdt>(), std::forward<functor>(f));
+        std::for_each(input_data.cbegin<input_tdt, false>(), input_data.cend<input_tdt, false>(), std::forward<functor>(f));
+    }
+
+    template <
+            typename input_tdt,
+            typename functor,
+            typename = std::enable_if_t<std::is_invocable_r_v<void, functor, ColumnData::Enumeration<typename input_tdt::DataTypeTag::raw_type, true>>>>
```
Comment (vasil-pashov) [inline cpp/arcticdb/column_store/column.hpp:688]: nit: We can use concepts now instead of enable if, it's a bit easier on the eyes

File: cpp/arcticdb/column_store/column.hpp [hunk 3]
```diff
@@ -708,8 +733,49 @@ class Column {
...
         auto output_data = output_column.data();
-        std::transform(left_input_data.cbegin<left_input_tdt>(), left_input_data.cend<left_input_tdt>(), right_input_data.cbegin<right_input_tdt>(), output_data.begin<output_tdt>(), std::forward<functor>(f));
+        auto output_it = output_data.begin<output_tdt, false, false>();
+
+        if (!left_input_column.is_sparse() && !right_input_column.is_sparse()) {
+            // Both dense, use std::transform over the shorter column to avoid going out-of-bounds
+            if (left_input_column.row_count() <= right_input_column.row_count()) {
+                std::transform(left_input_data.cbegin<left_input_tdt, false>(), left_input_data.cend<left_input_tdt, false>(), right_input_data.cbegin<right_input_tdt, false>(), output_it, [f = std::forward<functor>(f)](auto left_value, auto right_value) {
+                    return f(left_value, right_value);
+                });
```
Comment (vasil-pashov) [inline cpp/arcticdb/column_store/column.hpp:745]: Can't we use this instead?
```suggestion
                std::transform(left_input_data.cbegin<left_input_tdt, false>(), left_input_data.cend<left_input_tdt, false>(), right_input_data.cbegin<right_input_tdt, false>(), output_it, std::forward<functor>(f));
```

File: cpp/arcticdb/column_store/column.hpp [hunk 4]
```diff
@@ -708,8 +733,49 @@ class Column {
...
+            } else {
+                std::transform(right_input_data.cbegin<left_input_tdt, false>(), right_input_data.cend<left_input_tdt, false>(), left_input_data.cbegin<right_input_tdt, false>(), output_it, [f = std::forward<functor>(f)](auto right_value, auto left_value) {
+                    return f(left_value, right_value);
+                });
+            }
+        } else if (left_input_column.is_sparse() && right_input_column.is_sparse()) {
+            // Both sparse, only project rows in the intersection of on-bits from both sparse maps
```
Comment (vasil-pashov) [inline cpp/arcticdb/column_store/column.hpp:752]: Maybe I missed it but where do we compute the intersection?

File: cpp/arcticdb/column_store/column_data.hpp [hunk 5]
```diff
@@ -132,73 +132,134 @@ struct ColumnData {
  * ColumnData is just a thin wrapper that helps in iteration over all the blocks in the column
  */
 
+    template<typename RawType, bool constant>
+    struct Enumeration {
+        ssize_t idx_{0};
+        RawType* ptr_{nullptr};
+
+        inline std::conditional_t<constant, const ssize_t&, ssize_t&> idx() const {
```
[the remark this answers is not in the document]
Comment (vasil-pashov) [reply cpp/arcticdb/column_store/column_data.hpp:140]: Is idx_ supposed to be changed from outside at all? I could be missing something but it looks like we this should be just
```
ssize_t idx() const {
    return idx_;
}
```

File: cpp/arcticdb/column_store/column_data_random_accessor.hpp [hunk 6]
```diff
@@ -0,0 +1,192 @@
...
+        // Cache the base pointers of each block, as typed_block->data() has an if statement for internal vs external
+        base_ptrs_.reserve(parent->num_blocks());
+        while (auto typed_block = parent->next<TDT>()) {
+            base_ptrs_.emplace_back(reinterpret_cast<const RawType *>(typed_block->data()));
+        }
+    }
+
+    RawType at(size_t idx) const {
+        auto block_offset = idx % values_per_block_;
+        auto block_idx = (idx / values_per_block_);
```
Comment (vasil-pashov) [inline cpp/arcticdb/column_store/column_data_random_accessor.hpp:68]: nit: [std::div](https://en.cppreference.com/w/cpp/numeric/math/div)

File: cpp/arcticdb/util/preconditions.hpp [hunk 7]
```diff
@@ -68,6 +68,19 @@ namespace internal {
     constexpr auto raise = check<code>.raise;
 }
 
+namespace debug {
+#ifdef DEBUG_BUILD
```
Comment (vasil-pashov) [inline cpp/arcticdb/util/preconditions.hpp:72]: Debug, only checks are awesome

File: cpp/arcticdb/column_store/column.hpp (hunk 4 above)
Comment (alexowens90) [reply cpp/arcticdb/column_store/column.hpp:752]: `initialise_output_column` sets the sparse map of the output

File: cpp/arcticdb/column_store/column_data.hpp (hunk 5 above)
[the remark this answers is not in the document]
Comment (alexowens90) [reply cpp/arcticdb/column_store/column_data.hpp:140]: I think @vasil-pashov is right, with a non-const iterator users should be able to modify the value, but it doesn't make sense to modify the index.

[the remark this answers is not in the document]
Comment (alexowens90) [reply cpp/arcticdb/column_store/column_data.hpp:140]: @JohanMabille I believe your comment still applies to `value()` though

File: cpp/arcticdb/column_store/column.hpp [hunk 8]
```diff
@@ -708,8 +733,49 @@ class Column {
...
+            for (auto left_it = left_input_data.cbegin<left_input_tdt, true, true>();
+                 left_it != left_input_data.cend<left_input_tdt, true, true>() && left_it->idx() < right_column_row_count;
+                 ++left_it) {
+                *output_it++ = f(left_it->value(), right_accessor.at(left_it->idx()));
+            }
+        } else if (!left_input_column.is_sparse() && right_input_column.is_sparse()) {
+            // One sparse, one dense. Use the enumerating forward iterator over the sparse column as it is more efficient than random access
+            auto left_accessor = random_accessor<left_input_tdt>(&left_input_data);
+            const auto left_column_row_count = left_input_column.row_count();
+            for (auto right_it = right_input_data.cbegin<right_input_tdt, true, true>();
```
[the remark this answers is not in the document]
Comment (alexowens90) [reply cpp/arcticdb/column_store/column.hpp:773]: Because of `enumeration`, the combinatorics mean that you would then have:

- `cbegin_sparse_enumerated`
- `cbegin_dense_enumerated`
- `cbegin_sparse_non_enumerated`
- `cbegin_dense_non_enumerated`

and similar for `begin`, `end`, and `cend`. I'll swap the bools for enums though so make it more readable at the calling sites.

File: cpp/arcticdb/column_store/column_data.hpp (hunk 5 above)
[the remark this answers is not in the document]
Comment (JohanMabille) [reply cpp/arcticdb/column_store/column_data.hpp]: Not sure, `value` can be seen as the equivalent of `operator*` for iterators. Strictly speaking, assigning through `value` won't change the state of `Enumeration`.

File: cpp/arcticdb/CMakeLists.txt [hunk 9]
```diff
@@ -756,71 +755,73 @@ if(${TEST})
 
     set(unit_test_srcs
             async/test/test_async.cpp
-            codec/test/test_codec.cpp
```
Comment (vasil-pashov) [inline cpp/arcticdb/CMakeLists.txt:759]: Leaving a remainder to bring back the tests

File: cpp/arcticdb/column_store/column.hpp [hunk 10]
```diff
@@ -693,74 +716,175 @@ class Column {
...
+                               output_it,
+                               std::forward<functor>(f));
+            }
+        } else if (left_input_column.is_sparse() && right_input_column.is_sparse()) {
+            // Both sparse, only project rows in the intersection of on-bits from both sparse maps
+            auto left_accessor = random_accessor<left_input_tdt>(&left_input_data);
+            auto right_accessor = random_accessor<right_input_tdt>(&right_input_data);
+            // TODO: experiment with more efficient bitset traversal methods
+            // https://github.com/tlk00/BitMagic/tree/master/samples/bvsample25
+            for (auto set_bit = output_column.sparse_map().first(); set_bit < output_column.sparse_map().end(); ++set_bit) {
```
Comment (willdealtry) [inline cpp/arcticdb/column_store/column.hpp:759]: Do we know how expensive calculating sparse_map().end() is? It might be safer to hoist it up out of the loop control

File: cpp/arcticdb/column_store/column.hpp [hunk 11]
```diff
@@ -693,74 +716,175 @@ class Column {
...
+            }
+        } else if (left_input_column.is_sparse() && right_input_column.is_sparse()) {
+            // Both sparse, only check the intersection of on-bits from both sparse maps
+            auto bits_to_check = left_input_column.sparse_map() & right_input_column.sparse_map();
+            initialise_output_bitset(bits_to_check, sparse_missing_value_output, output_bitset);
+            auto left_accessor = random_accessor<left_input_tdt>(&left_input_data);
+            auto right_accessor = random_accessor<right_input_tdt>(&right_input_data);
+            // TODO: experiment with more efficient bitset traversal methods
+            // https://github.com/tlk00/BitMagic/tree/master/samples/bvsample25
+            for (auto set_bit = bits_to_check.first(); set_bit < bits_to_check.end(); ++set_bit) {
```
Comment (willdealtry) [inline cpp/arcticdb/column_store/column.hpp:858]: as above

File: cpp/arcticdb/processing/aggregation.cpp [hunk 12]
```diff
@@ -261,55 +247,42 @@ namespace
...
-                                                if constexpr(T == Extremum::MAX) {
-                                                    val.value_ = std::max(val.value_, curr);
-                                                } else {
-                                                    val.value_ = std::min(val.value_, curr);
-                                                }
-                                            }
+                    details::visit_type(input_column->column_->type().data_type(), [&input_column, &groups, &out_ptr] (auto col_tag) {
+                        using col_type_info = ScalarTypeInfo<decltype(col_tag)>;
+                        if constexpr(!is_sequence_type(col_type_info::data_type)) {
+                            Column::for_each_enumerated<typename col_type_info::TDT>(*input_column->column_, [&groups, &out_ptr](auto enumerating_it) {
```
Comment (willdealtry) [inline cpp/arcticdb/processing/aggregation.cpp:263]: This is so much clearer than what was there before, as well as helping people to avoid performance pitfalls. Very exciting!

File: cpp/arcticdb/processing/operation_dispatch_binary.hpp [hunk 13]
```diff
@@ -51,72 +51,67 @@ VariantData binary_membership(const ColumnWithStrings& column_with_strings, Valu
...
+        if constexpr(std::is_same_v<Func, IsNotInOperator&&>) {
+            return FullResult{};
+        } else {
+            return EmptyResult{};
+        }
+    }
+
+    util::BitSet output_bitset;
+    constexpr auto sparse_missing_value_output = std::is_same_v<Func, IsNotInOperator&&>;
+    details::visit_type(column_with_strings.column_->type().data_type(),[&] (auto col_tag) {
```
Comment (willdealtry) [inline cpp/arcticdb/processing/operation_dispatch_binary.hpp:67]: Not necessarily for now, but we should provide a helper method on ColumnWithStrings to make it more readable, as it's such a common thing to do (i.e. to get the data_type()

**Review by willdealtry — APPROVED** [review]
